### ISSUE TITLE
how to run this code...

### ISSUE THREAD

**Issue by gicheonkang** [ishay2b/VanillaCNN#10]
hi I didn't understand your comment about running a code. I have a error like

Traceback (most recent call last):
  File "mainLoop.py", line 141, in <module>
    dataRowsTrain_CSV = createDataRowsFromCSV(CSV_TRAIN, DataRow.DataRowFromNameBoxInterlaved, DATA_PATH)
  File "/home/chon/VanillaCNN/python/DataRow.py", line 40, in createDataRowsFromCSV
    with open(csvFilePath, 'r') as csvfile:
IOError: [Errno 2] No such file or directory: '/home/chon/VanillaCNN/data/trainImageList.txt'

I think this is because data set is not downloaded..
what should I type the command?
python mainLoop.py STEPS=[FULL_STEPS]  <-- It isn't work

**Comment by ishay2b** [comment]
This should run full steps in mainLoop.py script:
`STEPS = AFW_STEPS + AFLW_STEPS`

**Comment by gicheonkang** [comment]
Can you explain the difference between testSetPickle, testSetHD5 ??

I have a error when I include both of steps..

**Comment by ishay2b** [comment]
Hd5 is used by caffe. Pickle used by python mini scripts. What error do you get?

**Comment by gicheonkang** [comment]
I solved problem
Reason is variable name in your code

AFLW_STEPS=['downloadALFW', ~~~~]
...
if 'downloadAFLW' in STEPS:
The AFLW, ALFW ^_^

And I have another question. do you have VanillaCNN.caffemodel's source code?
I want to read about specific structures of it.

**Comment by ishay2b** [comment]
A python notebook to run training is found here: https://github.com/ishay2b/VanillaCNN/blob/master/python/VanillaNoteBook.ipynb

The readme file describes important parts of the code.
The original article is found here: http://www.openu.ac.il/home/hassner/projects/tcnn_landmarks/

**Comment by gicheonkang** [comment]
No, I don't know where the source code is.
About model ( details of CNN Layers, Activation functions ... )
python notebook has a code of above them?

**Comment by ishay2b** [comment]
The python code is in the rep you are commenting on: https://github.com/ishay2b/VanillaCNN
see the python folder. Best if you use the notebook. 

The  caffe prototxt deployment file: https://github.com/ishay2b/VanillaCNN/blob/master/ZOO/vanilla_deploy.prototxt
