### ISSUE TITLE
Why normalized-MSE? not Euclidean distance

### ISSUE THREAD

**Issue by gicheonkang** [ishay2b/VanillaCNN#11]
Hi I have a question about evaluating a error rate.
while profiling, I saw a code like below (in 'testAFW_TestSet')

```
for i, dataRow in enumerate(dataRowsAFW_Valid):
        dataRow40 = dataRow.copyCroppedByBBox(dataRow.fbbox)
        image, lm_0_5 = predictor.preprocess(dataRow40.image, dataRow40.landmarks())
        prediction = predictor.predict(image)
        
        # Using normalized-MSE
        testErrorAFW.add(lm_0_5, prediction)
        dataRow40.prediction = (prediction+0.5)*40
```
you use mse_normlized with ground-truth, prediction
Is there any particular reason why you use MSE ?

**Comment by ishay2b** [comment]
Same as been used in the article, the error is lessen when the eyes are closer.

**Comment by gicheonkang** [comment]
Thank you for your reply.
I have one more question. In paper, there is no reason why vanillaCNN model uses 
absolute hyperbolic tangent(activation function).

I tested ReLU, but the accuracy is worse. Can you explain the reason?

**Comment by ishay2b** [comment]
@gicheonkang Most issues in this database is due to very little data. 
ReLU has more dynamic range and gives better results where data is available.
Here ,my guess is that the Abs Tangent little dynamic range (less degrees of freedom) prevents over-fitting.
