### ISSUE TITLE
train error，Creating layer loss

### ISSUE THREAD

**Issue by janicevidal** [ishay2b/VanillaCNN#14]
MemoryError
![_20180315_111313](https://user-images.githubusercontent.com/29887681/37442628-62a1fad4-2842-11e8-95bc-b19c954a3605.png)
why？seeking for help

**Comment by ishay2b** [comment]
Hi,
Looks like a memory issue.
The batch size is too big for your computer, try reduce batch size.
If you run out on gpu, try using cpu instead, I trained it using cpu with 8G ram.
