### ISSUE TITLE
How to generate mean data of the train set?

### ISSUE THREAD

**Issue by wuqiangch** [ishay2b/VanillaCNN#3]
@ishay2b Thanks for your sharing code. What are your databases to be used to train your new model? How to generata the mean data of train set ? Have your try gray image? Maybe it is more quickly.

**Comment by ishay2b** [comment]
The code itself has the links to download so feel free to check (mainLoop.py).
A new commit was added to generate the mean and std images of the train sets. check 'calcTrainSetMean' 
Grey is faster but less accurate.
