### ISSUE TITLE
Mean and STD images

### ISSUE THREAD

**Issue by fishman2008** [ishay2b/VanillaCNN#5]
Do you have the code to compute the mean and std images? I know that the mean can be computed by averaging the training images in general, but just not sure if the calculation will be the same as yours. It might go through some scale transformations?

If this question is duplicated, please delete it. Thanks.

**Comment by ishay2b** [comment]
Please pull latest commit, edit mainLoop.py:62 with:
STEPS =['trainSetHD5', 'calcTrainSetMean'] 
and run mainLoop.py
This will recalculate the mean and std and write it to: trainMean.png and trainSTD.png
